apiVersion: v1
kind: PersistentVolumeClaim
metadata:

  name: fluentd-vol-1
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  