apiVersion: v1
kind: PersistentVolume
metadata:
  name: v1
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/openebs/local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - infra-2-prod-1
  claimRef:
    name: fluentd-vol-1
         
  #hostPath:
   # path: "/home/storage/efk"
